import NavBar from "@/components/navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <div className="h-full">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
